import {
  LuMenu,
  LuX,
  LuLayoutPanelLeft,
  LuKeyRound,
  LuPencil,
  LuSun,
  LuMoon,
  LuTrash2,
  LuCopy,
  LuCheck,
  LuUser,
  LuCpu,
  LuInbox,
  LuFilter,
  LuPlus,
  LuInfo,
  LuMoveUp,
  LuMoveDown,
  LuCircleUser,
  LuLogOut,
  LuUserCog,
  LuChevronRight,
  LuLock,
} from 'react-icons/lu';

export const Icons = {
  Menu: LuMenu,
  Close: LuX,
  Sidebar: LuLayoutPanelLeft,
  Key: LuKeyRound,
  Edit: LuPencil,
  Moon: LuMoon,
  Sun: LuSun,
  Delete: LuTrash2,
  Copy: LuCopy,
  Check: LuCheck,
  NormalUser: LuUser,
  ServiceApp: LuCpu,
  ServiceRequest: LuInbox,
  Filter: LuFilter,
  AddNew: LuPlus,
  Info: LuInfo,
  Approve: LuCheck,
  Reject: LuX,
  ArrowUp: LuMoveUp,
  ArrowDown: LuMoveDown,
  User: LuCircleUser,
  Logout: LuLogOut,
  AssignRole: LuUserCog,
  ChevronRight: LuChevronRight,
  Lock: LuLock,
};
